version: "3"
services:
  project:
    build:
      context: ./project
      dockerfile: ./Dockerfile
    restart: ${RESTART_POLICY}
    ports:
      - ${HOST_HTTP_PORT}:9581
    volumes:
      - ${PROJECT_PATH}/docker/project/entrypoint.sh:/entrypoint.sh
      - ${PROJECT_PATH}/docker/project/nginx.${MODE}.conf:/etc/nginx/nginx.conf
      - ${PROJECT_PATH}/data:/project/data
      - ${PROJECT_PATH}/node_modules:/project/node_modules
      - ${PROJECT_PATH}/packages/:/project/packages
      - ${PROJECT_PATH}/.eslintrc:/project/.eslintrc
      - ${PROJECT_PATH}/package.json:/project/package.json
      - ${PROJECT_PATH}/package-lock.json:/project/package-lock.json
      - ${PROJECT_PATH}/tsconfig.base.json:/project/tsconfig.base.json
      - ${PROJECT_PATH}/tsconfig.json:/project/tsconfig.json
    environment:
      - MODE=${MODE}
      - DATAPREP_IMPORT_FOLDER=${DATAPREP_IMPORT_FOLDER}
      - DATAPREP_EXPORT_FOLDER=${DATAPREP_EXPORT_FOLDER}
