name: deploy-data

on:
  workflow_run:
    workflows: [CI-TEST]
    types: [completed]
    branches: [dev]
  push:
    branches:
      - dev
    paths:
      - "packages/dataprep/**"
      - "data/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PUBLIC_URL: "/lasso"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Dataprep install
        run: |
          npm install

      - name: Generate data
        run: |
          cd packages/dataprep
          npm run exec

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: packages/client/public/data # The folder the action should deploy.
          target-folder: data
