name: I18N

on:
  push:
    branches:
      - dev
    paths:
      - "packages/client/**"

jobs:
  i18n:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm
        run: npm install -g npm@next-8

      - name: Install
        run: npm install

      - name: Transifex
        env:
          TRANSIFEX_TOKEN: ${{ secrets.TRANSIFEX_TOKEN }}
          TRANSIFEX_SECRET: ${{ secrets.TRANSIFEX_SECRET }}
        run: npm run i18n --workspace=@lasso/client
